# Generated by Django 3.2.13 on 2022-06-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgame',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='bgame',
            name='min_play',
            field=models.IntegerField(default=2, verbose_name='最低プレイ人数'),
        ),
        migrations.AddField(
            model_name='bgame',
            name='weight',
            field=models.CharField(blank=True, choices=[('軽量級', '軽量級'), ('中量級', '中量級'), ('重量級', '重量級')], max_length=50, null=True, verbose_name='重さ'),
        ),
    ]
