# Generated by Django 3.2.13 on 2022-06-29 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgame', '0002_auto_20220629_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgame',
            options={'verbose_name': 'ボードゲーム', 'verbose_name_plural': 'ボードゲーム'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='wantplay',
            options={'verbose_name': '遊んでみたい', 'verbose_name_plural': '遊んでみたい'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
