# Generated by Django 3.2.13 on 2022-06-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgame', '0004_auto_20220629_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '興味あり',
                'verbose_name_plural': '興味あり',
            },
        ),
        migrations.AddField(
            model_name='wantplay',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wantplay',
            name='bgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.bgame'),
        ),
        migrations.AlterField(
            model_name='wantplay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wantplay',
            constraint=models.UniqueConstraint(fields=('bgame', 'user'), name='wantplay_unique'),
        ),
        migrations.AddField(
            model_name='interest',
            name='bgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgame.bgame'),
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('bgame', 'user'), name='interest_unique'),
        ),
    ]
