# Generated by Django 3.2.13 on 2022-07-06 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgame', '0006_alter_bgame_want_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgame',
            name='interest',
            field=models.ManyToManyField(related_name='interests', through='bgame.Interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bgame',
            name='want_play',
            field=models.ManyToManyField(related_name='wantplays', through='bgame.WantPlay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='bgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_bgame', to='bgame.bgame'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wantplay',
            name='bgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wantplay_bgame', to='bgame.bgame'),
        ),
        migrations.AlterField(
            model_name='wantplay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wantplay_interest', to=settings.AUTH_USER_MODEL),
        ),
    ]
